-- Ejecutar en el SQL Editor de Supabase (proyecto zknhnivznhifhhpexipy)
--
-- ============================================================================
-- MIGRACION: "etiquetas" pasan de ser un 3er nivel de jerarquia a un catalogo
-- GLOBAL transversal (marketplaces: Mercado Libre, Amazon, Walmart, Fedex...).
-- ============================================================================
--
-- PROBLEMA que resuelve:
--   Hoy las "Etiquetas" de la UI son filas de subcategorias_tutoriales, y cada
--   una cuelga de UN modulo (subcategorias_tutoriales.modulo_id). Por eso
--   "Mercado Libre" existe DUPLICADO: ids 1, 4 y 5, una fila por modulo (24, 35,
--   40). Son entidades distintas sin relacion entre si -> no se puede filtrar
--   "todo lo de Mercado Libre", y agregar Fedex obliga a recrearlo en cada modulo.
--
-- SOLUCION:
--   - etiquetas          : catalogo global, UNA fila por marketplace.
--   - modulo_etiquetas    : que etiquetas aplican a que modulo (preserva el
--                           dropdown filtrado por modulo de /upload y /edit).
--   - tutoriales.etiqueta_id : nueva FK al catalogo global.
--
-- Esta migracion es ADITIVA y reversible: NO borra subcategorias_tutoriales ni
-- tutoriales.subcategoria_id. Se dejan intactas hasta verificar que la app
-- funciona con etiqueta_id; la limpieza va al final, comentada.
--
-- IMPORTANTE: correr TODO el archivo de una sola vez (los pasos dependen entre si).

-- ----------------------------------------------------------------------------
-- 1. Catalogo global de etiquetas
-- ----------------------------------------------------------------------------
create table if not exists public.etiquetas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  activo boolean not null default true,
  orden int not null default 0,
  creado_por uuid references auth.users(id),
  fecha_creacion timestamptz not null default now()
);

-- Evita que se vuelvan a crear duplicados como los actuales. Case-insensitive:
-- "Amazon" y "amazon" se consideran la misma etiqueta.
create unique index if not exists idx_etiquetas_nombre_unico
  on public.etiquetas (lower(nombre));

-- ----------------------------------------------------------------------------
-- 2. Relacion N-a-N: que etiquetas se ofrecen en cada modulo
-- ----------------------------------------------------------------------------
create table if not exists public.modulo_etiquetas (
  modulo_id bigint not null references public.modulos_tutoriales(id) on delete cascade,
  etiqueta_id bigint not null references public.etiquetas(id) on delete cascade,
  primary key (modulo_id, etiqueta_id)
);

create index if not exists idx_modulo_etiquetas_etiqueta
  on public.modulo_etiquetas(etiqueta_id);

-- ----------------------------------------------------------------------------
-- 3. Poblar el catalogo desde las subcategorias existentes (colapsa duplicados)
--    Las 3 "Mercado Libre" (ids 1,4,5) -> 1 sola fila. bool_or: la etiqueta
--    queda activa si CUALQUIERA de sus copias lo estaba.
-- ----------------------------------------------------------------------------
insert into public.etiquetas (nombre, activo)
select s.nombre, bool_or(s.activo)
from public.subcategorias_tutoriales s
group by s.nombre
on conflict (lower(nombre)) do nothing;

-- ----------------------------------------------------------------------------
-- 4. Mapear que modulos ofrecian cada etiqueta -> modulo_etiquetas
--    (subcategoria "Mercado Libre" en modulos 24,35,40  ->  3 filas apuntando
--    a la MISMA etiqueta global)
-- ----------------------------------------------------------------------------
insert into public.modulo_etiquetas (modulo_id, etiqueta_id)
select distinct s.modulo_id, e.id
from public.subcategorias_tutoriales s
join public.etiquetas e on lower(e.nombre) = lower(s.nombre)
on conflict (modulo_id, etiqueta_id) do nothing;

-- ----------------------------------------------------------------------------
-- 5. Nueva columna en tutoriales + backfill desde subcategoria_id
-- ----------------------------------------------------------------------------
alter table public.tutoriales
  add column if not exists etiqueta_id bigint references public.etiquetas(id);

create index if not exists idx_tutoriales_etiqueta_id
  on public.tutoriales(etiqueta_id);

update public.tutoriales t
set etiqueta_id = e.id
from public.subcategorias_tutoriales s
join public.etiquetas e on lower(e.nombre) = lower(s.nombre)
where t.subcategoria_id = s.id
  and t.etiqueta_id is null;

-- ----------------------------------------------------------------------------
-- 6. RLS del catalogo (mismo patron que el resto: authenticated hace todo)
-- ----------------------------------------------------------------------------
alter table public.etiquetas enable row level security;
alter table public.modulo_etiquetas enable row level security;

drop policy if exists "Authenticated lee etiquetas" on public.etiquetas;
create policy "Authenticated lee etiquetas"
  on public.etiquetas for select to authenticated using (true);
drop policy if exists "Authenticated escribe etiquetas" on public.etiquetas;
create policy "Authenticated escribe etiquetas"
  on public.etiquetas for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated lee modulo_etiquetas" on public.modulo_etiquetas;
create policy "Authenticated lee modulo_etiquetas"
  on public.modulo_etiquetas for select to authenticated using (true);
drop policy if exists "Authenticated escribe modulo_etiquetas" on public.modulo_etiquetas;
create policy "Authenticated escribe modulo_etiquetas"
  on public.modulo_etiquetas for all to authenticated using (true) with check (true);

-- ============================================================================
-- VERIFICACION (correr y revisar a ojo antes de tocar el codigo):
-- ============================================================================
-- select id, nombre, activo from public.etiquetas order by nombre;
--   -> "Mercado Libre" debe aparecer UNA sola vez.
--
-- select e.nombre, count(*) as modulos
--   from public.modulo_etiquetas me
--   join public.etiquetas e on e.id = me.etiqueta_id
--   group by e.nombre order by e.nombre;
--   -> "Mercado Libre" debe decir 3 modulos.
--
-- select count(*) filter (where subcategoria_id is not null) as con_subcat,
--        count(*) filter (where etiqueta_id is not null)     as con_etiqueta
--   from public.tutoriales where activo;
--   -> ambos numeros deben coincidir (todo lo etiquetado migro).

-- ============================================================================
-- LIMPIEZA (NO correr todavia). Solo despues de que la app use etiqueta_id y
-- hayas confirmado en produccion que nada quedo huerfano:
-- ============================================================================
-- alter table public.tutoriales drop column if exists subcategoria_id;
-- drop table if exists public.subcategorias_tutoriales;
