-- Ejecutar en el SQL Editor de Supabase (proyecto zknhnivznhifhhpexipy)
--
-- Examen por MODULO (no por video). Un modulo tiene a lo mas un examen;
-- cada examen tiene varias preguntas de opcion multiple, con sus opciones
-- y la respuesta correcta guardadas como jsonb (mismo patron que ya usamos
-- para "checklist" y "documentos" en tutoriales).
--
-- Esto crea el contenido del examen (preguntas + opciones). Trackear
-- intentos/calificaciones de cada usuario seria una tabla aparte, una vez
-- que definamos como se rinde el examen.

create table if not exists public.examenes_modulo (
  id bigint generated by default as identity primary key,
  modulo_id bigint not null references public.modulos_tutoriales(id) unique,
  titulo text not null,
  descripcion text,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now(),
  creado_por uuid references auth.users(id)
);

create table if not exists public.examen_preguntas (
  id bigint generated by default as identity primary key,
  examen_id bigint not null references public.examenes_modulo(id) on delete cascade,
  pregunta text not null,
  -- arreglo de opciones: [{ "texto": "...", "es_correcta": true|false }, ...]
  opciones jsonb not null,
  orden int not null default 0,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now()
);

create index if not exists idx_examen_preguntas_examen_id
  on public.examen_preguntas(examen_id);

-- Un intento de examen por usuario. Se permite repetir el examen, asi que
-- esto es un historial (una fila por cada vez que alguien lo presenta), no
-- un "estado" unico por usuario.
-- usuario_nombre se guarda tal cual (denormalizado), igual que autor_nombre
-- en comentarios_tutoriales, porque el cliente no puede hacer join a
-- auth.users con la anon key.
create table if not exists public.examen_intentos (
  id bigint generated by default as identity primary key,
  examen_id bigint not null references public.examenes_modulo(id) on delete cascade,
  usuario_id uuid not null references auth.users(id),
  usuario_nombre text not null,
  -- calificacion en escala 0-10; aprobado si es >= 8.
  -- "real" y no "numeric": los numeric/decimal los devuelve Supabase como
  -- string en vez de number, lo cual rompe .toFixed() en el frontend.
  calificacion real not null,
  aprobado boolean not null,
  -- lo que respondio, para poder revisar el intento despues:
  -- [{ "pregunta_id": 1, "opcion_elegida": "..." }, ...]
  respuestas jsonb not null,
  fecha_intento timestamptz not null default now()
);

create index if not exists idx_examen_intentos_examen_usuario
  on public.examen_intentos(examen_id, usuario_id, fecha_intento);

-- Ultima vez que un usuario vio cada video completo, una fila por par
-- (tutorial, usuario) que se actualiza (upsert) cada vez que lo vuelve a
-- ver. Alcanza con la ultima fecha porque el unico uso es comparar contra
-- la fecha del intento fallido para saber si lo volvio a ver despues.
create table if not exists public.visualizaciones_tutoriales (
  tutorial_id bigint not null references public.tutoriales(id) on delete cascade,
  usuario_id uuid not null references auth.users(id),
  fecha_visualizacion timestamptz not null default now(),
  primary key (tutorial_id, usuario_id)
);

-- MIGRACION: si ya habias creado "visualizaciones_tutoriales" con la version
-- anterior de este script (con "id" autoincremental, sin llave compuesta),
-- el "create table if not exists" de arriba no la toca y el upsert de la app
-- falla con "no unique or exclusion constraint matching ON CONFLICT".
-- Corre esto para migrarla a la llave compuesta (conserva, por cada par
-- tutorial+usuario, solo la visualizacion mas reciente):
--
-- delete from public.visualizaciones_tutoriales a
-- using public.visualizaciones_tutoriales b
-- where a.tutorial_id = b.tutorial_id
--   and a.usuario_id = b.usuario_id
--   and a.fecha_visualizacion < b.fecha_visualizacion;
--
-- alter table public.visualizaciones_tutoriales drop column if exists id;
--
-- alter table public.visualizaciones_tutoriales
--   add primary key (tutorial_id, usuario_id);

-- MIGRACION: si ya habias creado "examen_intentos" con "calificacion numeric",
-- conviertela a "real" (ver comentario arriba de por que):
--
-- alter table public.examen_intentos
--   alter column calificacion type real using calificacion::real;
