-- Ejecutar en el SQL Editor de Supabase (proyecto zknhnivznhifhhpexipy)
--
-- ============================================================================
-- BIBLIOTECA: seccion para cargar PDFs, docs y cualquier archivo que NO sea
-- video, organizados por la misma taxonomia que los tutoriales
-- (categoria -> modulo -> etiqueta) mas la posibilidad de documentos
-- transversales que no cuelgan de ningun modulo.
-- ============================================================================
--
-- REQUISITO: correr ANTES docs/migrate_etiquetas.sql (esto referencia public.etiquetas).
--
-- STORAGE: reusa el bucket privado existente "documentos-tutoriales" con el
-- prefijo de ruta "biblioteca/". No se crea un bucket nuevo: seria la misma
-- config y las mismas politicas RLS que el actual. Las lecturas se hacen con
-- signed URLs (createSignedUrl), igual que los documentos de tutoriales.

-- ----------------------------------------------------------------------------
-- 1. Tabla de documentos de la biblioteca
--    A diferencia de tutoriales.documentos (jsonb colgado de un video), aca
--    cada documento es una fila propia -> se puede filtrar, ordenar y paginar,
--    y puede existir SIN estar ligado a ningun tutorial.
-- ----------------------------------------------------------------------------
create table if not exists public.biblioteca_documentos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text,
  -- ruta del objeto dentro del bucket privado "documentos-tutoriales"
  -- (ej: "biblioteca/1699999999_manual.pdf"). NO es una URL publica.
  path text not null,
  nombre_archivo text not null,
  mime_type text,
  tamano_bytes bigint,
  -- Ubicacion en la taxonomia. TODAS opcionales: un documento puede ser
  -- transversal (modulo_id null) o aplicar a un marketplace concreto sin
  -- importar el modulo (solo etiqueta_id).
  modulo_id bigint references public.modulos_tutoriales(id) on delete set null,
  etiqueta_id bigint references public.etiquetas(id) on delete set null,
  -- Opcional: ligar el documento a un tutorial concreto. Permite migrar mas
  -- adelante los tutoriales.documentos (jsonb) a esta tabla si se quiere.
  tutorial_id bigint references public.tutoriales(id) on delete set null,
  activo boolean not null default true,     -- soft-delete, como el resto
  orden int not null default 0,
  creado_por uuid references auth.users(id),
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz
);

create index if not exists idx_biblioteca_modulo   on public.biblioteca_documentos(modulo_id);
create index if not exists idx_biblioteca_etiqueta on public.biblioteca_documentos(etiqueta_id);
create index if not exists idx_biblioteca_tutorial on public.biblioteca_documentos(tutorial_id);

alter table public.biblioteca_documentos enable row level security;

drop policy if exists "Authenticated lee biblioteca" on public.biblioteca_documentos;
create policy "Authenticated lee biblioteca"
  on public.biblioteca_documentos for select to authenticated using (true);
drop policy if exists "Authenticated escribe biblioteca" on public.biblioteca_documentos;
create policy "Authenticated escribe biblioteca"
  on public.biblioteca_documentos for all to authenticated using (true) with check (true);

-- ----------------------------------------------------------------------------
-- 2. Politicas de STORAGE que hoy faltan (UPDATE/DELETE en documentos-tutoriales)
--    En setup_documentos.sql estan comentadas, por eso al quitar un documento en
--    /edit el archivo queda huerfano en el bucket. La biblioteca tiene mucho mas
--    churn de archivos, asi que se habilitan aca. Idempotente.
-- ----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'Usuarios autenticados actualizan documentos-tutoriales'
  ) then
    create policy "Usuarios autenticados actualizan documentos-tutoriales"
      on storage.objects for update to authenticated
      using (bucket_id = 'documentos-tutoriales')
      with check (bucket_id = 'documentos-tutoriales');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'Usuarios autenticados eliminan documentos-tutoriales'
  ) then
    create policy "Usuarios autenticados eliminan documentos-tutoriales"
      on storage.objects for delete to authenticated
      using (bucket_id = 'documentos-tutoriales');
  end if;
end $$;

-- ============================================================================
-- VERIFICACION:
--   select * from public.biblioteca_documentos limit 1;   -- tabla existe, vacia
--   select policyname from pg_policies
--     where tablename='objects' and policyname ilike '%documentos-tutoriales%';
--     -> deben aparecer 4 politicas (select, insert, update, delete)
-- ============================================================================
